# Generated by Django 5.2.4 on 2025-07-12 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('eclinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicperformanceanalytics',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_analytics', to='eclinic.clinic'),
        ),
        migrations.AlterUniqueTogether(
            name='consultationanalytics',
            unique_together={('date',)},
        ),
        migrations.AddField(
            model_name='doctorperformanceanalytics',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='platformmetrics',
            unique_together={('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='revenueanalytics',
            unique_together={('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='systemperformancemetrics',
            unique_together={('date',)},
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useranalytics',
            unique_together={('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='clinicperformanceanalytics',
            unique_together={('clinic', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorperformanceanalytics',
            unique_together={('doctor', 'date')},
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'activity_type'], name='user_activi_user_id_62eedd_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['timestamp'], name='user_activi_timesta_8378ef_idx'),
        ),
    ]
