# Generated by Django 5.2.4 on 2025-07-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('video_call', 'Video Call')], default='video_call', max_length=20),
        ),
    ]
