# Generated by Django 5.2.4 on 2025-07-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultation_consultation_type'),
        ('eclinic', '0005_alter_clinic_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='eclinic.clinic'),
        ),
    ]
