# Generated by Django 5.2.4 on 2025-07-30 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultation_clinic'),
        ('doctors', '0004_alter_doctorslot_unique_together_doctorslot_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='booked_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_consultations', to='doctors.doctorslot'),
        ),
    ]
