# Generated by Django 5.0.1 on 2025-08-15 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultationreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='When patient was checked in', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, help_text='Admin who checked in the patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ready_for_consultation_at',
            field=models.DateTimeField(blank=True, help_text='When patient was marked ready for consultation', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ready_marked_by',
            field=models.ForeignKey(blank=True, help_text='Admin who marked patient as ready', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_markings_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('patient_checked_in', 'Patient Checked In'), ('ready_for_consultation', 'Ready for Consultation'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=25),
        ),
    ]
