# Generated by Django 5.0.1 on 2025-09-01 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_consultation_checked_in_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='reschedule_approved',
            field=models.BooleanField(default=False, help_text='Whether reschedule has been approved'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='reschedule_approved_at',
            field=models.DateTimeField(blank=True, help_text='When reschedule was approved', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='reschedule_approved_by',
            field=models.ForeignKey(blank=True, help_text='Who approved the reschedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_approvals_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='reschedule_reason',
            field=models.TextField(blank=True, help_text='Reason for reschedule request'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='reschedule_requested',
            field=models.BooleanField(default=False, help_text='Whether reschedule has been requested'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='reschedule_requested_at',
            field=models.DateTimeField(blank=True, help_text='When reschedule was requested', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='reschedule_requested_by',
            field=models.ForeignKey(blank=True, help_text='Who requested the reschedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('patient_checked_in', 'Patient Checked In'), ('ready_for_consultation', 'Ready for Consultation'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled'), ('overdue', 'Overdue')], default='scheduled', max_length=25),
        ),
    ]
