# Generated by Django 5.0.1 on 2025-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_consultation_reschedule_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, help_text='When reschedule was applied', null=True),
        ),
    ]
