# Generated by Django 5.2.4 on 2025-07-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescriptionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='body',
            field=models.TextField(blank=True, help_text='Main prescription body (diagnosis, medicines, etc.)'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='footer',
            field=models.TextField(blank=True, help_text='Footer section for eClinic info'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='header',
            field=models.TextField(blank=True, help_text='Header section for eClinic info'),
        ),
    ]
