# Generated by Django 5.2.4 on 2025-08-06 05:09

import django.db.models.deletion
import prescriptions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_auto_20250730_1538'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='Generated prescription PDF', upload_to=prescriptions.models.prescription_pdf_upload_path)),
                ('version_number', models.PositiveIntegerField(help_text='Version number of this prescription')),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current version')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('header_image', models.ImageField(blank=True, help_text='Header image used for this PDF', null=True, upload_to='prescription_headers/')),
                ('footer_image', models.ImageField(blank=True, help_text='Footer image used for this PDF', null=True, upload_to='prescription_footers/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('checksum', models.CharField(blank=True, help_text='MD5 checksum of the file', max_length=64)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_prescription_pdfs', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_versions', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Prescription PDF',
                'verbose_name_plural': 'Prescription PDFs',
                'db_table': 'prescription_pdfs',
                'ordering': ['-version_number', '-generated_at'],
                'unique_together': {('prescription', 'version_number')},
            },
        ),
    ]
