# Generated by Django 5.0.1 on 2025-08-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_add_prescription_pdf_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='secondary_diagnosis',
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_previous_history',
            field=models.TextField(blank=True, help_text="Patient's previous medical history"),
        ),
    ]
