# Generated by Django 5.0.1 on 2025-09-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_remove_prescription_secondary_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Blood Tests, Imaging, etc.)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investigation Category',
                'verbose_name_plural': 'Investigation Categories',
                'db_table': 'investigation_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the test', max_length=200)),
                ('code', models.CharField(blank=True, help_text='Test code/abbreviation', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what the test measures')),
                ('normal_range', models.CharField(blank=True, help_text='Normal range values', max_length=200)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=50)),
                ('is_fasting_required', models.BooleanField(default=False, help_text='Whether fasting is required')),
                ('preparation_instructions', models.TextField(blank=True, help_text='Patient preparation instructions')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost of the test', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this test is available')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='prescriptions.investigationcategory')),
            ],
            options={
                'verbose_name': 'Investigation Test',
                'verbose_name_plural': 'Investigation Tests',
                'db_table': 'investigation_tests',
                'ordering': ['category__order', 'order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PrescriptionInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', help_text='Priority level of the test', max_length=20)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for this test')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of investigation in prescription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='prescriptions.prescription')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='prescriptions.investigationtest')),
            ],
            options={
                'verbose_name': 'Prescription Investigation',
                'verbose_name_plural': 'Prescription Investigations',
                'db_table': 'prescription_investigations',
                'ordering': ['order', 'created_at'],
                'unique_together': {('prescription', 'test')},
            },
        ),
    ]
