# Generated by Django 5.0.1 on 2025-09-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_investigationcategory_investigationtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionpdf',
            name='is_mobile_generated',
            field=models.BooleanField(default=False, help_text='Whether this PDF was generated from mobile consultation'),
        ),
    ]
