# Generated by Django 5.0.1 on 2025-09-22 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0007_prescriptionpdf_is_mobile_generated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(help_text='Prescription image uploaded from mobile', upload_to='prescriptions/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_mobile_upload', models.BooleanField(default=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_images', to='prescriptions.prescription')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_prescription_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription Image',
                'verbose_name_plural': 'Prescription Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
