# Generated by Django 5.0.1 on 2025-10-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_prescriptionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedication',
            name='quantity',
            field=models.CharField(blank=True, help_text='Quantity (e.g., 10 tablets, 1 bottle)', max_length=100),
        ),
    ]
