# Generated by Django 5.0.1 on 2025-10-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0009_add_quantity_field'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE prescription_medications DROP COLUMN IF EXISTS timing_display_text;",
            reverse_sql="ALTER TABLE prescription_medications ADD COLUMN timing_display_text VARCHAR(500);"
        ),
        migrations.RunSQL(
            "ALTER TABLE prescription_medications DROP COLUMN IF EXISTS timing_multiple;",
            reverse_sql="ALTER TABLE prescription_medications ADD COLUMN timing_multiple JSONB;"
        ),
    ]
