# Generated by Django 5.0.1 on 2025-10-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0010_auto_20251015_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedication',
            name='timing_display_text',
            field=models.CharField(blank=True, help_text='Human-readable timing display text (e.g., Before Breakfast, Lunch & Dinner)', max_length=200),
        ),
    ]
