# Generated by Django 5.0.1 on 2025-08-14 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientprofile_blood_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('medical_records', 'Medical Records'), ('documents', 'Documents'), ('notes', 'Notes'), ('profile', 'Profile'), ('prescriptions', 'Prescriptions')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('session_duration', models.IntegerField(blank=True, help_text='Session duration in seconds', null=True)),
                ('records_accessed', models.IntegerField(default=0, help_text='Number of records accessed')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_access_logs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient Access Log',
                'verbose_name_plural': 'Patient Access Logs',
                'db_table': 'patient_access_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['patient', 'timestamp'], name='patient_acc_patient_e8dd96_idx'), models.Index(fields=['admin', 'timestamp'], name='patient_acc_admin_i_b5f76a_idx'), models.Index(fields=['access_type', 'timestamp'], name='patient_acc_access__85fd3a_idx')],
            },
        ),
    ]
