# Generated by Django 5.2.4 on 2025-07-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorslot_delete_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_anniversary',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
