# Generated by Django 5.2.4 on 2025-07-30 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultation_clinic'),
        ('doctors', '0003_doctorprofile_date_of_anniversary_and_more'),
        ('eclinic', '0007_clinic_consultation_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic for which this slot is created', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_slots', to='eclinic.clinic'),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slot', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='is_booked',
            field=models.BooleanField(default=False, help_text='Whether this slot is booked for a consultation'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorslot',
            unique_together={('doctor', 'clinic', 'date', 'start_time', 'end_time')},
        ),
    ]
