# Generated by Django 5.2.4 on 2025-07-30 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_booked_slot'),
        ('doctors', '0004_alter_doctorslot_unique_together_doctorslot_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorslot',
            name='consultation',
        ),
        migrations.AddField(
            model_name='doctorslot',
            name='booked_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slots', to='consultations.consultation'),
        ),
    ]
