# Generated by Django 3.2.7 on 2025-07-31 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultation_booked_slot'),
        ('doctors', '0005_remove_doctorslot_consultation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, help_text='Whether doctor is currently connected')),
                ('is_logged_in', models.BooleanField(default=False, help_text='Whether doctor is authenticated')),
                ('is_available', models.BooleanField(default=True, help_text='Whether doctor is available for consultations')),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('consulting', 'In Consultation'), ('busy', 'Busy'), ('away', 'Away'), ('offline', 'Offline'), ('break', 'On Break'), ('unavailable', 'Unavailable')], default='offline', help_text='Current status of the doctor', max_length=20)),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('last_logout', models.DateTimeField(blank=True, help_text='Last logout timestamp', null=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True, help_text='When status was last updated')),
                ('status_note', models.TextField(blank=True, help_text='Optional note about current status')),
                ('auto_away_threshold', models.IntegerField(default=15, help_text='Minutes of inactivity before auto-away status')),
                ('current_consultation', models.ForeignKey(blank=True, help_text='Currently active consultation if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_doctor_status', to='consultations.consultation')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='doctors.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Status',
                'verbose_name_plural': 'Doctor Statuses',
                'ordering': ['-last_activity'],
            },
        ),
    ]
