# Generated by Django 5.2.4 on 2025-08-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctorstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_duration',
            field=models.PositiveIntegerField(default=5, help_text='Duration in minutes'),
        ),
    ]
