# Generated by Django 5.0.1 on 2025-08-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_update_consultation_duration_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='signature',
            field=models.FileField(blank=True, help_text="Doctor's digital signature file", null=True, upload_to='doctor_signatures/'),
        ),
    ]
