# Generated by Django 5.0.1 on 2025-08-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctorprofile_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('General Medicine', 'General Medicine'), ('Gynecology', 'Gynecology'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Ophthalmology', 'Ophthalmology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry'), ('Pulmonology', 'Pulmonology'), ('Radiology', 'Radiology'), ('Surgery', 'Surgery'), ('Urology', 'Urology'), ('Other', 'Other')], max_length=50),
        ),
    ]
