# Generated by Django 5.0.1 on 2025-08-14 12:44

from django.db import migrations


def convert_specialization_values(apps, schema_editor):
    """Convert old lowercase specialization values to new capitalized values"""
    DoctorProfile = apps.get_model('doctors', 'DoctorProfile')
    
    # Mapping of old values to new values
    specialization_mapping = {
        'cardiology': 'Cardiology',
        'dermatology': 'Dermatology',
        'endocrinology': 'Endocrinology',
        'gastroenterology': 'Gastroenterology',
        'general_medicine': 'General Medicine',
        'gynecology': 'Gynecology',
        'neurology': 'Neurology',
        'oncology': 'Oncology',
        'orthopedics': 'Orthopedics',
        'pediatrics': 'Pediatrics',
        'psychiatry': 'Psychiatry',
        'pulmonology': 'Pulmonology',
        'urology': 'Urology',
        'other': 'Other',
    }
    
    # Update all doctor profiles
    for profile in DoctorProfile.objects.all():
        old_value = profile.specialization
        if old_value in specialization_mapping:
            profile.specialization = specialization_mapping[old_value]
            profile.save()


def reverse_convert_specialization_values(apps, schema_editor):
    """Reverse the conversion (for rollback)"""
    DoctorProfile = apps.get_model('doctors', 'DoctorProfile')
    
    # Reverse mapping
    specialization_mapping = {
        'Cardiology': 'cardiology',
        'Dermatology': 'dermatology',
        'Endocrinology': 'endocrinology',
        'Gastroenterology': 'gastroenterology',
        'General Medicine': 'general_medicine',
        'Gynecology': 'gynecology',
        'Neurology': 'neurology',
        'Oncology': 'oncology',
        'Orthopedics': 'orthopedics',
        'Pediatrics': 'pediatrics',
        'Psychiatry': 'psychiatry',
        'Pulmonology': 'pulmonology',
        'Urology': 'urology',
        'Other': 'other',
    }
    
    # Update all doctor profiles
    for profile in DoctorProfile.objects.all():
        new_value = profile.specialization
        if new_value in specialization_mapping:
            profile.specialization = specialization_mapping[new_value]
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_update_specialization_choices'),
    ]

    operations = [
        migrations.RunPython(
            convert_specialization_values,
            reverse_convert_specialization_values
        ),
    ]
