# Generated by Django 5.0.1 on 2025-08-14 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_convert_specialization_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_url', models.URLField(help_text='URL to the signature file in cloud storage')),
                ('file_path', models.CharField(help_text='Path to the signature file in storage', max_length=500)),
                ('file_name', models.CharField(help_text='Original filename of the signature', max_length=200)),
                ('file_size', models.PositiveIntegerField(help_text='Size of the signature file in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this signature is currently active')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_info', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Signature',
                'verbose_name_plural': 'Doctor Signatures',
                'db_table': 'doctor_signatures',
            },
        ),
    ]
