# Generated by Django 5.0.1 on 2025-08-18 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_doctorsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_duration',
            field=models.PositiveIntegerField(default=5, help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
