# Generated by Django 5.0.1 on 2025-08-18 03:22

from django.db import migrations, models


def update_consultation_durations(apps, schema_editor):
    """Update existing doctor profiles to have consultation_duration = 5 if not set or if outside valid range"""
    DoctorProfile = apps.get_model('doctors', 'DoctorProfile')
    
    # Update all doctor profiles that have consultation_duration < 5 or > 15 or null
    DoctorProfile.objects.filter(
        models.Q(consultation_duration__lt=5) | 
        models.Q(consultation_duration__gt=15) | 
        models.Q(consultation_duration__isnull=True)
    ).update(consultation_duration=5)


def reverse_update_consultation_durations(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_update_consultation_duration_default'),
    ]

    operations = [
        migrations.RunPython(update_consultation_durations, reverse_update_consultation_durations),
    ]
