# Generated by Django 5.0.1 on 2025-08-18 03:30

from django.db import migrations


def update_all_consultation_durations_to_5(apps, schema_editor):
    """Update ALL doctor profiles to have consultation_duration = 5"""
    DoctorProfile = apps.get_model('doctors', 'DoctorProfile')
    
    # Update ALL doctor profiles to have consultation_duration = 5
    updated_count = DoctorProfile.objects.all().update(consultation_duration=5)
    print(f"Updated {updated_count} doctor profiles to have consultation_duration = 5")


def reverse_update_all_consultation_durations_to_5(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_update_existing_consultation_durations'),
    ]

    operations = [
        migrations.RunPython(update_all_consultation_durations_to_5, reverse_update_all_consultation_durations_to_5),
    ]
