# Generated by Django 5.2.4 on 2025-07-15 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic', '0002_clinicappointment_clinicdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='accepts_walk_ins',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='emergency_services',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='lab_services',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='pharmacy_available',
        ),
        migrations.AddField(
            model_name='clinic',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administered_clinics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(choices=[('virtual_clinic', 'Virtual Clinic')], default='virtual_clinic', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClinicDoctor',
        ),
    ]
