# Generated by Django 5.2.4 on 2025-07-15 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic', '0003_remove_clinic_accepts_walk_ins_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='administered_clinics', to=settings.AUTH_USER_MODEL),
        ),
    ]
