# Generated by Django 5.2.4 on 2025-07-22 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic', '0004_alter_clinic_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='admin',
            field=models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='administered_clinic', to=settings.AUTH_USER_MODEL),
        ),
    ]
