# Generated by Django 5.2.4 on 2025-07-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic', '0005_alter_clinic_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='logo',
        ),
    ]
