# Generated by Django 5.2.4 on 2025-07-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic', '0006_remove_logo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='consultation_duration',
            field=models.PositiveIntegerField(default=15, help_text='Duration of each consultation slot in minutes'),
        ),
    ]
