# Generated by Django 3.2.7 on 2025-07-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('info', 'Info'), ('success', 'Success')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('system', 'System'), ('doctors', 'Doctors'), ('clinics', 'Clinics'), ('payments', 'Payments'), ('analytics', 'Analytics'), ('security', 'Security')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
